from enum import Enum


class TextType(Enum):
    DEFAULT = "DEFAULT"
    SNAKE = "SNAKE"
    WALL = "WALL"
    FRUIT = "FRUIT"
    SCORE_BAR = "SCORE_BAR"
    FINAL_SCORE = "FINAL_SCORE"
    TITLE = "TITLE"
    INFO = "INFO"
    GAME_OVER = "GAME_OVER"
    HIGH_SCORE_TITLE = "HIGH_SCORE_TITLE"
    HIGH_SCORE_TEXT = "HIGH_SCORE_TEXT"
    HIGH_SCORE_TEXT_ACTIVE = "HIGH_SCORE_TEXT_ACTIVE"
